"""empty message

Revision ID: 04e9c792ba85
Revises: 7216f0a8d3de
Create Date: 2021-08-08 14:26:04.809505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e9c792ba85'
down_revision = '7216f0a8d3de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activate_user_code', sa.Column('last_user_attempt_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activate_user_code', 'last_user_attempt_time')
    # ### end Alembic commands ###
