"""empty message

Revision ID: 52959204b358
Revises: 670e01aa4491
Create Date: 2021-09-27 15:44:53.337373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52959204b358'
down_revision = '670e01aa4491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_attempt', sa.Column('creation_time', sa.DateTime(), nullable=True))
    op.add_column('teacher_feedback', sa.Column('creation_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_feedback', 'creation_time')
    op.drop_column('student_attempt', 'creation_time')
    # ### end Alembic commands ###
