"""empty message

Revision ID: 633da2c5dd23
Revises: bc29bcaad459
Create Date: 2021-08-16 10:20:56.309826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633da2c5dd23'
down_revision = 'bc29bcaad459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problem_status', 'title',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('role', 'title',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('role', 'title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('problem_status', 'title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
