"""empty message

Revision ID: 670e01aa4491
Revises: 14eb4ea47e9b
Create Date: 2021-08-31 16:28:52.130917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670e01aa4491'
down_revision = '14eb4ea47e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempt', 'have_new_content_for_teacher')
    op.drop_column('attempt', 'have_new_content_for_student')
    op.add_column('session', sa.Column('have_new_content_for_teacher', sa.Boolean(), nullable=False))
    op.add_column('session', sa.Column('have_new_content_for_student', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'have_new_content_for_student')
    op.drop_column('session', 'have_new_content_for_teacher')
    op.add_column('attempt', sa.Column('have_new_content_for_student', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('attempt', sa.Column('have_new_content_for_teacher', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
