"""empty message

Revision ID: 7216f0a8d3de
Revises: fc05584ce74f
Create Date: 2021-08-06 15:38:20.441673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7216f0a8d3de'
down_revision = 'fc05584ce74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('university_group', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'university_group')
    # ### end Alembic commands ###
