"""empty message

Revision ID: 94d8deb1ca45
Revises: 05e0c14efc8b
Create Date: 2021-10-12 16:55:43.709518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d8deb1ca45'
down_revision = '05e0c14efc8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('isClose', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'isClose')
    # ### end Alembic commands ###
