"""empty message

Revision ID: 99509ad87b6b
Revises: 1e062c302660
Create Date: 2022-02-08 13:17:16.069393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99509ad87b6b'
down_revision = '1e062c302660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_discipline')
    # ### end Alembic commands ###
