"""empty message

Revision ID: ac548edcd667
Revises: 94d8deb1ca45
Create Date: 2021-11-28 12:28:01.049642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac548edcd667'
down_revision = '94d8deb1ca45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_problem_id_fkey', 'session', type_='foreignkey')
    op.drop_column('session', 'problem_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('problem_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('session_problem_id_fkey', 'session', 'problem', ['problem_id'], ['id'])
    # ### end Alembic commands ###
