"""empty message

Revision ID: c6ab5bca36bd
Revises: f66584e79f44
Create Date: 2021-08-24 07:59:48.078386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ab5bca36bd'
down_revision = 'f66584e79f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'rejection_reason')
    # ### end Alembic commands ###
