"""empty message

Revision ID: e769e8885a5e
Revises: ce9b7259915d
Create Date: 2021-11-28 12:35:37.090682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e769e8885a5e'
down_revision = 'ce9b7259915d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('problem_id', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'session', 'problem', ['problem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'problem_id')
    # ### end Alembic commands ###
