"""empty message

Revision ID: f66584e79f44
Revises: a9da12b27497
Create Date: 2021-08-23 15:01:56.233573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66584e79f44'
down_revision = 'a9da12b27497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('problem_complexity_id', sa.Integer(), nullable=True))
    op.drop_constraint('problem_problem_complexity_is_fkey', 'problem', type_='foreignkey')
    op.create_foreign_key(None, 'problem', 'problem_complexity', ['problem_complexity_id'], ['id'])
    op.drop_column('problem', 'problem_complexity_is')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('problem_complexity_is', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.create_foreign_key('problem_problem_complexity_is_fkey', 'problem', 'problem_complexity', ['problem_complexity_is'], ['id'])
    op.drop_column('problem', 'problem_complexity_id')
    # ### end Alembic commands ###
